theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  - scope:
      path: "google545f589585dfc62e.html"
    values:
      sitemap: false
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
google_measurement_id: G-9ZVEKX6BBN
# google_ad_client: ca-pub-5588329234018540
