description: <span>trzsz is a simple file transfer tools,</span> <span>which similar to lrzsz ( rz / sz ),</span> <span>and compatible with tmux.</span>
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
google_measurement_id: G-9ZVEKX6BBN
# google_ad_client: ca-pub-5588329234018540
